### ISSUE TITLE
Any upcoming character counter changes?

### ISSUE THREAD

**Issue by denisk20** [twitter/twitter-text#167] opened 2017-02-27 15:42 UTC
Hello,
Wanted to ask if any changes in the libraries are planned to reflect this?
https://blog.twitter.com/express-even-more-in-140-characters
For example if a tweet is a reply then any user handles at the beginning and media URLs at the end shouldn't count add to character count.

Thanks!

**Comment by andypiper** [comment] 2017-02-27 16:09
Duplicate of #117

**Closed by andypiper** 2017-02-27 16:09 UTC
