### ISSUE TITLE
1.13.4 crashes on Android

### ISSUE THREAD

**Issue by mariotaku** [twitter/twitter-text#111] opened 2016-03-12 06:36 UTC
desc: U_ILLEGAL_ARGUMENT_ERROR

Seems Regex pattern is too long.

**Comment by luaz** [comment] 2016-06-03 09:07
ERR: stack=java.lang.ExceptionInInitializerError
                                                                      at com.twitter.Extractor.extractHashtagsWithIndices(Extractor.java:381)
                                                                      at com.twitter.Extractor.extractHashtagsWithIndices(Extractor.java:351)
                                                                      at com.twitter.Extractor.extractHashtags(Extractor.java:337)

Caused by: java.util.regex.PatternSyntaxException: U_ILLEGAL_ARGUMENT_ERROR
                                                                  (((?:[^A-Z0-9@＠$#＃‪-‮]|^))((https?://)?((?:(?>(?:[\p{Alnum}\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u024f\u0253\u0254\u0256\u0257\u0259\u025b\u0263\u0268\u026f\u0272\u0289\u028b\u02bb\u0300-\u036f\u1e00-\u1eff][[\p{Alnum}\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u024f\u0253\u0254\u0256\u0257\u0259\u025b\u0263\u0268\u026f\u0272\u0289\u028b\u02bb\u0300-\u036f\u1e00-\u1eff]\-_]*)?[\p{Alnum}\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u024f\u0253\u0254\u0256\u0257\u0259\u025b\u0263\u0268\u026f\u0272\u0289\u028b\u02bb\u0300-\u036f\u1e00-\u1eff]\.)+(?:(?:[\p{Alnum}\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u024f\u0253\u0254\u0256\u0257\u0259\u025b\u0263\u0268\u026f\u0272\u0289\u028b\u02bb\u0300-\u036f\u1e00-\u1eff][[\p{Alnum}\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u024f\u0253\u0254\u0256\u0257\u0259\u025b\u0263\u0268\u026f\u0272\u0289\u028b\u02bb\u0300-\u036f\u1e00-\u1eff]\-]*)?[\p{Alnum}\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u024f\u0253\u0254\u0256\u0257\u0259\u025b\u0263\u0268\u026f\u0272\u0289\u028b\u02bb\u0300-\u036f\u1e00-\u1eff]\.)(?:(?:(?:abb|abbott|abogado|academy|accenture|accountant|accountants|aco|active|actor|ads|adult|aeg|aero|afl|agency|aig|airforce|airtel|allfinanz|alsace|amsterdam|android|apartments|app|aquarelle|archi|army|arpa|asia|associates|attorney|auction|audio|auto|autos|axa|azure|band|bank|bar|barcelona|barclaycard|barclays|bargains|bauhaus|bayern|bbc|bbva|bcn|beer|bentley|berlin|best|bet|bharti|bible|bid|bike|bing|bingo|bio|biz|black|blackfriday|bloomberg|blue|bmw|bnl|bnpparibas|boats|bond|boo|boots|boutique|bradesco|bridgestone|broker|brother|brussels|budapest|build|builders|business|buzz|bzh|cab|cafe|cal|camera|camp|cancerresearch|canon|capetown|capital|caravan|cards|care|career|careers|cars|cartier|casa|cash|casino|cat|catering|cba|cbn|ceb|center|ceo|cern|cfa|cfd|chanel|channel|chat|cheap|chloe|christmas|chrome|church|cisco|citic|city|claims|cleaning|click|clinic|clothing|cloud|club|coach|codes|coffee|college|cologne|com|commbank|community|company|computer|condos|construction|consulting|contractors|cooking|cool|coop|corsica|country|coupons|courses|credit|creditcard|cricket|crown|crs|cruises|cuisinella|cymru|cyou|dabur|dad|dance|date|dating|datsun|day|dclk|deals|degree|delivery|delta|democrat|dental|dentist|desi|design|dev|diamonds|diet|digital|direct|directory|discount|dnp|docs|dog|doha|domains|doosan|download|drive|durban|dvag|earth|eat|edu|education|email|emerck|energy|engineer|engineering|enterprises|epson|equipment|erni|esq|estate|eurovision|eus|events|everbank|exchange|expert|exposed|express|fage|fail|faith|family|fan|fans|farm|fashion|feedback|film|finance|financial|firmdale|fish|fishing|fit|fitness|flig

**Comment by joaoevangelista** [comment] 2016-08-20 16:55
Is there any workaround to this issue ?

**Comment by denisk20** [comment] 2016-09-26 18:54
Any update/workaround for this issue? It renders the library pretty much useless on Android.

**Comment by YutaSakata** [comment] 2016-09-29 09:33
I guess that there is no workaround because this is caused by exceptions thrown in initialization of static field.

**Comment by twuttke** [comment] 2016-09-29 19:42
I've proposed a few times that we get rid of the giant ascii whitelist of
TLDs and just allow all ascii tlds [a-z]+ if the url has an
http(s)://prefix.  If the url does not begin with a protocol, then use a
narrow whitelist of TLDs that can be assumed to be urls (like .com, .net,
.org, etc...)

Can you try cropping most of the TLDs out of the regex as an experiment
 and tell me if the long regex error stops happening?

**Comment by denisk20** [comment] 2017-02-27 14:35
This seems to have been fixed in 1.14.3.

**Comment by codemonkey3045** [comment] 2017-02-28 04:20
yes it was :)

**Closed by codemonkey3045** 2017-02-28 04:20 UTC
Labels: bug
